name: oppgave 18
on:
  workflow_dispatch:

jobs:
  job1:
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
            
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: 'Run cleanup script'
        uses: azure/powershell@v1
        with:
          inlineScript: ./funcApp/cleanup.ps1 -resourceGroupName 'martin-workshop-hpkyj2uioyyli'
          azPSVersion: "latest"

      - name: 'Logout from azure'
        uses: azure/powershell@v1 
        with:
          inlineScript: |
            Disconnect-AzAccount -Scope CurrentUser
            az Logout
            az cache purge
            az account clear
          azPSversion: "latest"